name: open_meteo_api
description: A Dart API Client for the Open-Meteo API.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.1.0"

dependencies:

  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  test: ^1.21.6
  very_good_analysis: ^3.0.2